# Generated by Django 2.0.6 on 2018-06-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rushcafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='rushcafe.MenuCategory'),
            preserve_default=False,
        ),
    ]
