# Generated by Django 2.0.6 on 2018-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushcafe', '0002_auto_20180610_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
