# Generated by Django 2.0.6 on 2018-06-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('rushcafe', '0003_auto_20180610_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='sessions.Session')),
            ],
        ),
    ]
